version: '3.8'

services:
  app:
    build:
      context: .
    init: true
    environment:
      - VIRTUAL_HOST=danielsh.here
    expose:
      - '5173'
    networks:
      - default
      - nginx-proxy
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    secrets:
      - environment

volumes:
  node_modules:
  yarn_cache:

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy

secrets:
  environment:
    file: .env
